name: Task Acknowledgment
on:
  issues:
    types: [opened]

jobs:
  acknowledge:
    if: github.event_name == 'issues' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Acknowledge task
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} \
            --body "Task received: **${{ github.event.issue.title }}**

WorkBuddy will process it and send results to your Gmail.

_auto-reply via Alistair Hub_"
        env:
          GH_TOKEN: ${{ github.token }}
